apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invapp-metrics
  name: invapp-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invapp-metrics
  template:
    metadata:
      labels:
        app: invapp-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
      - image: victorpoliushko/invapp-api
        name: invapp-api
        ports:
        - containerPort: 3000
        resources: {}
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: api-key
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: jwt-key
          - name: JWT_EXPIRE_IN
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: jwt-expiration-time
          - name: REFRESH_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: refresh-key
          - name: REFRESH_JWT_EXPIRE_IN
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: refresh-expiration-time
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: url
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: db-password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: db-name
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: db-port
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google-credentials
                key: client-id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-credentials
                key: client-secret
          - name: GOOGLE_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: google-credentials
                key: callback-url

